general_host = "localhost"

restaurant_grpc_service_port = 5001
restaurant_http_service_port = 5002

customer_grpc_service_port   = 5003
customer_http_service_port   = 5004

statistics_grpc_service_port = 5005
statistics_http_service_port = 5006

postgres_username = "yxtiblya"
postgres_password = "password"
postgres_host     = "localhost"
postgres_port     = 5432
postgres_dbname   = "MSFT"
postgres_ssl      = "disable"

# postgres_restaurant_dbname = "restaurant"
# postgres_consumer_dbname =   "consumer"
# postgres_statistics_dbname = "statistics"